SectionVerb {
	Value {
		FullySpecifiedUCM "1"
	}

	EnableSequence [
		cdev "hw:avsrt5514"
		cset "name='ADC1 Capture Volume' 55"
		cset "name='ADC2 Capture Volume' 55"
		cset "name='Sto1 ADC MIXL DMIC Switch' on"
		cset "name='Sto1 ADC MIXR DMIC Switch' on"
		cset "name='Sto2 ADC MIXL DMIC Switch' on"
		cset "name='Sto2 ADC MIXR DMIC Switch' on"
	]
}

SectionDevice."Internal Mic" {
	Value {
		CapturePCM "hw:avsrt5514,1"
		CaptureChannelMap "2 3 0 1 -1 -1 -1 -1 -1 -1 -1"
		DefaultNodeGain "2700"
	}
	EnableSequence [
		cdev "hw:avsrt5514"
		cset "name='Sto1 ADC MIXL DMIC Switch' on"
		cset "name='Sto1 ADC MIXR DMIC Switch' on"
		cset "name='Sto2 ADC MIXL DMIC Switch' on"
		cset "name='Sto2 ADC MIXR DMIC Switch' on"
	]
	DisableSequence [
		cdev "hw:avsrt5514"
		cset "name='Sto1 ADC MIXL DMIC Switch' off"
		cset "name='Sto1 ADC MIXR DMIC Switch' off"
		cset "name='Sto2 ADC MIXL DMIC Switch' off"
		cset "name='Sto2 ADC MIXR DMIC Switch' off"
	]
}
