# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# This file describes the Bazel-specific metadata (go/cros-bazel-metadata).

[bazel]

# This package only generates `.a` files.
generate_interface_libraries = false
