description "Switch bring-up persistent logkeeper"
author "switchroot bring-up"
oom score -100

start on started boot-services
stop on starting pre-shutdown

respawn
respawn limit unlimited

exec /usr/sbin/switch-logkeeper
