description "Switch bring-up Xorg fbdev server for Chrome"
author "chromium-os-dev@chromium.org"
start on starting ui
stop on stopping ui
respawn

# Killing the display server tears down the entire login session.
oom score never

console output
exec /sbin/switch-xorg-fbdev
