# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

THERMAL_ZONES=""

for i in $(seq 0 9); do
  THERMAL_ZONES="${THERMAL_ZONES} cpu${i}-thermal"
done

THERMAL_GOVERNOR="power_allocator"
