# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

description   "Load and verify modem FS image"
author        "chromium-os-dev@chromium.org"

start on starting rmtfs
task

# This is just a script. It shouldn't be caught by the OOM killer.
# If killed, LTE might not work on this boot.
oom score -100

exec /usr/share/cros/init/verify_fsg.sh
