# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

description     "Puff uprev quirk"
author          "asavery@chromium.org"

# Disable OOM killer as we must never fail.
oom score never

start on started ui

exec /usr/sbin/puff_quirk.sh
