#!/bin/sh
# Copyright 2022 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Init gpio for fibocom LTE module

disable_gpios() {
  # lte-w-disable
  gpioset gpiochip0 178=0

  # sar-detect
  gpioset gpiochip0 179=0

  # reset and sleep 20ms
  gpioset --mode=time -u 20000 gpiochip0 182=0

  # poweroff and sleep 100ms
  gpioset --mode=time -u 100000 gpiochip0 181=0

  # m2-power
  gpioset gpiochip0 180=0
}

enable_gpio() {
  local option="--mode=exit"
  local num="$1"
  local delay="$2"

  if [ "${delay}" -ne 0 ]; then
    option="--mode=time -u ${delay}"
  fi

  gpioset ${option} gpiochip0 ${num}=1
  ret=$?
  if [ "${ret}" -ne 0 ]; then
    disable_gpios
    exit "${ret}"
  fi
}

main() {
  local fw=$(cros_config /modem firmware-variant)
  if [ -z "${fw}" ]; then
    exit 0
  fi

  if [ "$1" = "on" ]; then
    # enable_gpio pin_num delay_microsec

    # lte-w-disable
    enable_gpio 178 0

    # sar-detect"
    enable_gpio 179 0

    # m2-power
    enable_gpio 180 2000

    # poweroff
    enable_gpio 181 14000

    #reset
    enable_gpio 182 0
  else
    disable_gpios
  fi
}
main "$@"
