# Copyright 2022 The ChromiumOS Authors.
# Distributed under the terms of the GNU General Public License v2

description     "Shutdown gpio power sequence for Fibocon LTE module"
author          "chromium-os-dev@chromium.org"

oom score -100

start on starting halt or starting reboot
task

exec lte_power_control off
