#!/bin/sh
# Copyright 2017 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[ "$(mosys platform version)" = "rev0" ] && echo "rev0"
