#!/bin/bash -e

# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

echo "Flashrom is currently broken on this platform" >&2
echo "See https://b.corp.google.com/issues/146216763" >&2

exit 1
