# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is the main toolchain - Required.
x86_64-cros-linux-gnu # x86_64-cros-linux-gnu, aarch64-cros-linux-gnu, etc...

# This is needed to build the AP/BIOS firmware - Optional.

# This is needed to build the EC firmware - Optional.
