# Copyright 2022 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CPUFREQ_GOVERNOR="ondemand"
CPUFREQ_SAMPLING_DOWN_FACTOR="12"
CPUFREQ_UP_THRESHOLD="50"
