#!/bin/bash

# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This quirk brings LP E-cores back online after system resume,
# restoring those disabled before suspend in powerd_pre_suspend_quirk.
# TODO(b/517844029): remove this quirk when this issue is fixed.

log_msg() {
  logger -t "powerd_post_resume_quirk" --id="$$" -- "$@"
}

enable_lp_core() {
  local core_id="$1"
  local lp_core_path="/sys/devices/system/cpu/cpu${core_id}/online"

  if [[ -f "${lp_core_path}" ]]; then
    echo 1 > "${lp_core_path}"
    log_msg "Enabled LP core ${core_id}"
  else
    log_msg "LP core ${core_id} does not exist"
  fi
}

total_cpus=$(nproc --all)
enable_lp_core "$(( total_cpus - 2 ))"
enable_lp_core "$(( total_cpus - 1 ))"
