# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

description     "Save the first random MAC address as a permanent one"
author          "chromium-os-dev@chromium.org"

start on started shill

script
  # Yes, mosys platform is deprecated, but it's not obvious what a better
  # solution here is and it seems other tools still use this.  This script
  # will be deleted soon anyway.
  this_board="$(mosys platform model)_$(mosys platform version)"
  this_mac="$(vpd -g wifi_mac0 || true)"

  # Only try this for early hardware and if no MAC was already set.
  if [ -z "${this_mac}" ]; then
    if [ "${this_board}" = "lazor_rev0" ] ||
       [ "${this_board}" = "lazor_rev1" ]; then
      # It seems the WiFi takes a little while to come up.  Since this is just
      # a hack, let's just try a few times.
      for i in $(seq 20); do
        using_mac="$(cat /sys/class/net/wlan0/address || true)"
        if [ -z "${using_mac}" ]; then
          sleep 5
          continue
        fi

        # Add a turd pointing back to us so people know it isn't real.
        vpd -s wifi_mac0_is_fake="See_b_162883167"

        # Take the first random one and jam it in.
        vpd -s wifi_mac0="${using_mac}"

        break
      done
    fi
  fi
end script
