SectionVerb {
	Value {
		FullySpecifiedUCM "1"
	}
}

SectionDevice."USB-C Headphone" {
	Value {
		PlaybackPCM "hw:Adapter,0"
		JackType "always"
		PlaybackRate "48000"
	}
}

SectionDevice."USB-C Mic" {
	Value {
		CapturePCM "hw:Adapter,0"
		MaxSoftwareGain "2000"
		JackType "always"
	}
}
