x86_64-pc-linux-gnu

# b/355044350: RISCV baremetal toolchain.
# Currently used for building FPMCU firmware; this firmware is independent of
# the CrOS board, so we put the toolchain in amd64-host.
riscv32-cros-elf
