SectionVerb {
	Value {
		FullySpecifiedUCM "1"
	}
	EnableSequence [
		cdev "hw:mt8192mt6359rt1"

		cset "name='Left DAC Playback Volume' 120"
		cset "name='Right DAC Playback Volume' 120"
		cset "name='Left Bypass Boost' 1"
		cset "name='Right Bypass Boost' 1"
		cset "name='Left Mono LR Select' Left"
		cset "name='Right Mono LR Select' Right"

		cset "name='I2S3_TINYCONN_CH1_MUX' 0"
		cset "name='I2S3_TINYCONN_CH2_MUX' 0"

		cset "name='MISO0_MUX' UL1_CH1"
		cset "name='MISO0_MUX' UL1_CH2"
		cset "name='UL_SRC_MUX' DMIC"
		cset "name='DMIC0_MUX' DMIC_DATA0"
		cset "name='ADDA_UL_Mux' MTKAIF"
	]
	DisableSequence [
		cdev "hw:mt8192mt6359rt1"
	]
}

SectionDevice."Speaker".0 {
	Value {
		PlaybackPCM "hw:mt8192mt6359rt1,0"
		DspName "speaker_eq"
	}
	EnableSequence [
		cdev "hw:mt8192mt6359rt1"
		cset "name='I2S3_CH1 DL1_CH1' 1"
		cset "name='I2S3_CH2 DL1_CH2' 1"
		cset "name='Left Spk Switch' 1"
		cset "name='Right Spk Switch' 1"
	]
	DisableSequence [
		cdev "hw:mt8192mt6359rt1"
		cset "name='Left Spk Switch' 0"
		cset "name='Right Spk Switch' 0"
		cset "name='I2S3_CH1 DL1_CH1' 0"
		cset "name='I2S3_CH2 DL1_CH2' 0"
	]
}

SectionDevice."Internal Mic".0 {
	Value {
		CapturePCM "hw:mt8192mt6359rt1,10"
		IntrinsicSensitivity "-2600"
		CaptureChannelMap "0 1 -1 -1 -1 -1 -1 -1 -1 -1 -1"
	}
	EnableSequence [
		cdev "hw:mt8192mt6359rt1"
		cset "name='MTKAIF_DMIC' 1"
		cset "name='UL1_CH1 ADDA_UL_CH1' 1"
		cset "name='UL1_CH2 ADDA_UL_CH2' 1"
	]
	DisableSequence [
		cdev "hw:mt8192mt6359rt1"
		cset "name='MTKAIF_DMIC' 0"
		cset "name='UL1_CH1 ADDA_UL_CH1' 0"
		cset "name='UL1_CH2 ADDA_UL_CH2' 0"
	]
}
