# If AC is plugged in, change the scaling_governor to performance.
# If AC is unplugged, change the scaling_governor to powersave.
#
CPUFREQ_GOVERNOR_ON_AC="performance"
CPUFREQ_GOVERNOR_OFF_AC="powersave"
