SectionVerb {
	Value {
		FullySpecifiedUCM "1"
	}
	EnableSequence [
		cdev "hw:mt8196rt5682s"
	]
	DisableSequence [
		cdev "hw:mt8196rt5682s"
	]
}

SectionDevice."Speaker".0 {
	Value {
		PlaybackPCM "hw:mt8196rt5682s,0"
	}
	EnableSequence [
		cdev "hw:mt8196rt5682s"
		cset "name='I2SOUT1_CH1 DL0_CH1' 1"
		cset "name='I2SOUT1_CH1 DL0_CH2' 1"
	]
	DisableSequence [
		cdev "hw:mt8196rt5682s"
		cset "name='I2SOUT1_CH1 DL0_CH1' 0"
		cset "name='I2SOUT1_CH1 DL0_CH2' 0"
	]
}

SectionDevice."Headphone".0 {
	Value {
		PlaybackPCM "hw:mt8196rt5682s,1"
		JackDev "mt8196_mt6681 Headset Jack"
		JackSwitch "2"
	}
	EnableSequence [
		cdev "hw:mt8196rt5682s"
		cset "name='I2SOUT6_CH1 DL1_CH1' 1"
		cset "name='I2SOUT6_CH1 DL0_CH2' 1"
	]
	DisableSequence [
		cdev "hw:mt8196rt5682s"
		cset "name='I2SOUT6_CH1 DL0_CH1' 0"
		cset "name='I2SOUT6_CH1 DL0_CH2' 0"
	]
}

SectionDevice."Front Mic".0 {
	Value {
		CapturePCM "hw:mt8196rt5682s,17"
		CaptureChannelMap "0 1 -1 -1 -1 -1 -1 -1 -1 -1 -1"
	}
	EnableSequence [
		cdev "hw:mt8196rt5682s"
		cset "name='ADDA_UL_Mux' AP_DMIC"
		cset "name='UL0_CH1 ADDA_UL_CH1' 1"
		cset "name='UL0_CH1 ADDA_UL_CH2' 1"
	]
	DisableSequence [
		cdev "hw:mt8196rt5682s"
		cset "name='UL0_CH1 ADDA_UL_CH1' 0"
		cset "name='UL0_CH1 ADDA_UL_CH2' 0"
	]
}

SectionDevice."Rear Mic".0 {
	Value {
		CapturePCM "hw:mt8196rt5682s,21"
		CaptureChannelMap "0 1 -1 -1 -1 -1 -1 -1 -1 -1 -1"
	}
	EnableSequence [
		cdev "hw:mt8196rt5682s"
		cset "name='ADDA_CH34_UL_Mux' AP_DMIC"
		cset "name='UL0_CH1 ADDA_UL_CH3' 1"
		cset "name='UL0_CH1 ADDA_UL_CH4' 1"
	]
	DisableSequence [
		cdev "hw:mt8196rt5682s"
		cset "name='UL0_CH1 ADDA_UL_CH3' 0"
		cset "name='UL0_CH1 ADDA_UL_CH4' 0"
	]
}

SectionDevice."Mic".0 {
	Value {
		CapturePCM "hw:mt8196rt5682s,29"
		JackDev "mt8196_mt6681 Headset Jack"
		JackSwitch "4"
		CaptureChannelMap "0 1 -1 -1 -1 -1 -1 -1 -1 -1 -1"
	}
	EnableSequence [
		cdev "hw:mt8196rt5682s"
		cset "name='UL26_CH1 I2SIN6_CH1' 0"
		cset "name='UL26_CH1 I2SIN6_CH2' 0"
	]
	DisableSequence [
		cdev "hw:mt8196rt5682s"
		cset "name='UL26_CH1 I2SIN6_CH1' 0"
		cset "name='UL26_CH1 I2SIN6_CH2' 0"
	]
}
