SectionVerb {
	Value {
		FullySpecifiedUCM "1"
	}

	EnableSequence [
		cdev "hw:avsrt5663"
		cset "name='Headphone Playback Volume' 16"
		cset "name='Headset Mic Switch' off"
		cset "name='STO1 ADC MIXL ADC1 Switch' on"
		cset "name='ADC Capture Volume' 35"
		cset "name='DAC L Mux' STO DAC MIXL"
		cset "name='DAC R Mux' STO DAC MIXR"
		cset "name='STO1 DAC MIXL DAC L Switch' on"
		cset "name='STO1 DAC MIXR DAC R Switch' on"
	]
}

SectionDevice."Headphone" {
	Value {
		PlaybackPCM "hw:avsrt5663,1"
		PlaybackMixerElem "DAC"
		JackDev "avs_rt5663 Headset Jack"
	}
	EnableSequence [
		cdev "hw:avsrt5663"

		cset "name='Headphone Jack Switch' on"
	]
	DisableSequence [
		cdev "hw:avsrt5663"

		cset "name='Headphone Jack Switch' off"
	]
}

SectionDevice."Mic" {
	Value {
		CapturePCM "hw:avsrt5663,1"
		CaptureMixerElem "Headset Mic"
		JackDev "avs_rt5663 Headset Jack"
	}
	EnableSequence [
		cdev "hw:avsrt5663"
		cset "name='Headset Mic Switch' on"

	]
	DisableSequence [
		cdev "hw:avsrt5663"
		cset "name='Headset Mic Switch' off"

	]
}
