[Sysprops]
# Disable LeGetVendorCapabilities
bluetooth.core.le.vendor_capabilities.enabled=false

# Configure the Scan parameters as the same as BlueZ.
# TODO(b:318772454): Consider remove this once QCA has a fix
bluetooth.core.classic.inq_length=8
# Inquiry scan interval  = N * 0.625 ms; value of 72 = 45ms
bluetooth.core.le.inquiry_scan_interval=72
# Inquiry scan window  = N * 0.625 ms; value of 18 = 11.25ms
bluetooth.core.le.inquiry_scan_window=18
